# coding: utf-8

scielo_headers = [
    'Extraction date',
    'Source',
    'Title (SciELO-Scopus-WOS)',
    'SciELO Publisher',
    'SciELO ISSN',
    'ISSNs',
    'Country',
    'SciELO or Scopus or WOSALL',
    'SciELO or Scopus or WOS1',
    'SciELO or Scopus or WOS2',
    'SciELO',
    'Scopus',
    'WOS ALL',
    'WOS1 (SCIE-SSCI-AHCI)',
    'WOS2 (ESCI)',

    # [Dados de SciELO]
    'SciELO ano de entrada na colecao',
    'SciELO Status (current = 1; not current = 0)',
    'SciELO ativo em 2018',
    'SciELO Thematic areas',
    'SciELO is agricultural sciences',
    'SciELO is applied social sciences',
    'SciELO is biological sciences',
    'SciELO is engineering',
    'SciELO is exact and earth sciences',
    'SciELO is health sciences',
    'SciELO is human sciences',
    'SciELO is linguistics, letters and arts',
    'SciELO is multidisciplinary',

    # [Dados de WoS]
    'WoS Title',
    'WoS Publisher',
    'WoS Thematic areas',

    # [Dados de Scopus]
    'Scopus Title',
    'Scopus Publisher',
    'Scopus all science classification codes asjc',
    'Scopus coverage',
    'Scopus top level life sciences',
    'Scopus top level social sciences',
    'Scopus top level physical sciences',
    'Scopus top level health sciences',
    'Scopus 1000 general',
    'Scopus 1100 agricultural and biological sciences',
    'Scopus 1200 arts and humanities',
    'Scopus 1300 biochemistry genetics and molecular biology',
    'Scopus 1400 business management and accounting',
    'Scopus 1500 chemical engineering',
    'Scopus 1600 chemistry',
    'Scopus 1700 computer science',
    'Scopus 1800 decision sciences',
    'Scopus 1900 earth and planetary sciences',
    'Scopus 2000 economics econometrics and finance',
    'Scopus 2100 energy',
    'Scopus 2200 engineering',
    'Scopus 2300 environmental science',
    'Scopus 2400 immunology and microbiology',
    'Scopus 2500 materials science',
    'Scopus 2600 mathematics',
    'Scopus 2700 medicine',
    'Scopus 2800 neuroscience',
    'Scopus 2900 nursing',
    'Scopus 3000 pharmacology toxicology and pharmaceutics',
    'Scopus 3100 physics and astronomy',
    'Scopus 3200 psychology',
    'Scopus 3300 social sciences',
    'Scopus 3400 veterinary',
    'Scopus 3500 dentistry',
    'Scopus 3600 health professions']
