# coding: utf-8

scielo_headers = [
 'Extraction date',
 'SciELO or Scopus or WoS',
 'SciELO',
 'Scopus',
 'WoS',
 'SciELO, Scopus and WoS',
 'SciELO and Scopus',
 'SciELO and WoS',
 'Scopus and WoS',
 'SciELO or Scopus',
 'Scopus or WoS',
 'SciELO or WoS',
 'SciELO and (Scopus ou WoS)',
 'SciELO and not (Scopus)',
 '(Scopus or WoS) and not SciELO',
 'Title (SciELO-Scopus-Wos)',

 # [Dados de SciELO]
 'ISSNs',
 'SciELO ISSN',
 'SciELO Status (current = 1; not current = 0)',
 'SciELO title thematic areas',
 'SciELO title is agricultural sciences',
 'SciELO title is applied social sciences',
 'SciELO title is biological sciences',
 'SciELO title is engineering',
 'SciELO title is exact and earth sciences',
 'SciELO title is health sciences',
 'SciELO title is human sciences',
 'SciELO title is linguistics, letters and arts',
 'SciELO title is multidisciplinary',
 'SciELO inclusion year',
 'SciELO stopping year',

 # [Sistema de Submissao 1 ou 0]
 'ScholarOne',
 'OJS',
 'Other systems',

 # [Dados de Google]
 'SciELO google scholar h5 2016',
 'SciELO google scholar m5 2016',

 # [Dados de DOAJ]
 'DOAJ',
 'DOAJ title',

 # [Dados de Scopus]
 'Scopus title',
 'Scopus Publisher Main',
 'Scopus all science classification codes asjc',
 'Scopus coverage',
 'Scopus top level life sciences',
 'Scopus top level social sciences',
 'Scopus top level physical sciences',
 'Scopus top level health sciences',
 'Scopus 1000 general',
 'Scopus 1100 agricultural and biological sciences',
 'Scopus 1200 arts and humanities',
 'Scopus 1300 biochemistry genetics and molecular biology',
 'Scopus 1400 business management and accounting',
 'Scopus 1500 chemical engineering',
 'Scopus 1600 chemistry',
 'Scopus 1700 computer science',
 'Scopus 1800 decision sciences',
 'Scopus 1900 earth and planetary sciences',
 'Scopus 2000 economics econometrics and finance',
 'Scopus 2100 energy',
 'Scopus 2200 engineering',
 'Scopus 2300 environmental science',
 'Scopus 2400 immunology and microbiology',
 'Scopus 2500 materials science',
 'Scopus 2600 mathematics',
 'Scopus 2700 medicine',
 'Scopus 2800 neuroscience',
 'Scopus 2900 nursing',
 'Scopus 3000 pharmacology toxicology and pharmaceutics',
 'Scopus 3100 physics and astronomy',
 'Scopus 3200 psychology',
 'Scopus 3300 social sciences',
 'Scopus 3400 veterinary',
 'Scopus 3500 dentistry',
 'Scopus 3600 health professions',
 'Scopus 2014 citescore',
 'Scopus 2014 sjr',
 'Scopus 2014 snip',
 'Scopus 2015 citescore',
 'Scopus 2015 sjr',
 'Scopus 2015 snip',
 'Scopus 2016 citescore',
 'Scopus 2016 sjr',
 'Scopus 2016 snip',

 # [Dados de Scimago]
 'Scimago title',
 'Scimago 2014 sjr',
 'Scimago 2014 sjr best quartile',
 'Scimago 2014 h index',
 'Scimago 2014 total docs 2015',
 'Scimago 2014 total docs 3years',
 'Scimago 2014 total refs',
 'Scimago 2014 total cites 3years',
 'Scimago 2014 citable docs 3years',
 'Scimago 2014 cites doc 2years',
 'Scimago 2014 ref doc',
 'Scimago 2015 sjr',
 'Scimago 2015 sjr best quartile',
 'Scimago 2015 h index',
 'Scimago 2015 total docs 2015',
 'Scimago 2015 total docs 3years',
 'Scimago 2015 total refs',
 'Scimago 2015 total cites 3years',
 'Scimago 2015 citable docs 3years',
 'Scimago 2015 cites doc 2years',
 'Scimago 2015 ref doc',
 'Scimago 2016 sjr',
 'Scimago 2016 sjr best quartile',
 'Scimago 2016 h index',
 'Scimago 2016 total docs 2015',
 'Scimago 2016 total docs 3years',
 'Scimago 2016 total refs',
 'Scimago 2016 total cites 3years',
 'Scimago 2016 citable docs 3years',
 'Scimago 2016 cites doc 2years',
 'Scimago 2016 ref doc',

 # [Dados de WoS]
 'WoS 2016 total cites',
 'WoS 2016 journal impact factor',
 'WoS 2016 impact factor without journal self cites',
 'WoS 2016 five years impact factor',
 'WoS 2016 immediacy index',
 'WoS 2016 citable items',
 'WoS 2016 cited half-life',
 'WoS 2016 citing half-life',
 'WoS 2016 eigenfactor score',
 'WoS 2016 article influence score',
 'WoS 2016 percentage articles in citable items',
 'WoS 2016 average journal impact factor percentile',
 'WoS 2016 normalized eigenfactor']
