# coding: utf-8

headers = [
    'Extraction date',
    'is_scielo',
    'is_scopus',
    'Title (SciELO-Scopus)',
    'Publiser name (SciELO-Scopus)',
    'SciELO ISSN',
    'ISSNs',
    'SciELO Status (current = 1; not current = 0)',
    'Country',

    # [Dados de JCR]
    'Scopus 2017 Citescore',
    'Scopus 2017 SJR',
    'Scopus 2017 SNIP',
    'Scopus URL',
    'Scopus ID',
    'active_or_inactive',
    'all_science_classification_codes_asjc',
    'coverage',
    'top_level_life_sciences',
    'top_level_social_sciences',
    'top_level_physical_sciences',
    'top_level_health_sciences',
    'c1000_general',
    'c1100_agricultural_and_biological_sciences',
    'c1200_arts_and_humanities',
    'c1300_biochemistry_genetics_and_molecular_biology',
    'c1400_business_management_and_accounting',
    'c1500_chemical_engineering',
    'c1600_chemistry',
    'c1700_computer_science',
    'c1800_decision_sciences',
    'c1900_earth_and_planetary_sciences',
    'c2000_economics_econometrics_and_finance',
    'c2100_energy',
    'c2200_engineering',
    'c2300_environmental_science',
    'c2400_immunology_and_microbiology',
    'c2500_materials_science',
    'c2600_mathematics',
    'c2700_medicine',
    'c2800_neuroscience',
    'c2900_nursing',
    'c3000_pharmacology_toxicology_and_pharmaceutics',
    'c3100_physics_and_astronomy',
    'c3200_psychology',
    'c3300_social_sciences',
    'c3400_veterinary',
    'c3500_dentistry',
    'c3600_health_professions'



]
