# coding: utf-8

scielo_headers = ['extraction_date',
 'SciELO ou Scopus ou WoS',
 'SciELO',
 'Scopus',
 'WoS',
 'SciELO, Scopus e WoS',
 'SciELO e Scopus',
 'SciELO e WoS',
 'Scopus e WoS',
 'SciELO ou Scopus',
 'Scopus ou WoS',
 'SciELO ou WoS',
 'SciELO e (Scopus ou WoS)',
 'SciELO e não (Scopus)',
 '(Scopus ou WoS) e não SciELO',
 'Título (SciELO-Scopus-Wos)',
 # [Dados de SciELO]
 'ISSNs',
 'SciELO ISSN',
 'SciELO Status (corrente = 1; não corrente = 0)',
 'SciELO title_thematic_areas',
 'SciELO title_is_agricultural_sciences',
 'SciELO title_is_applied_social_sciences',
 'SciELO title_is_biological_sciences',
 'SciELO title_is_engineering',
 'SciELO title_is_exact_and_earth_sciences',
 'SciELO title_is_health_sciences',
 'SciELO title_is_human_sciences',
 'SciELO title_is_linguistics,_letters_and_arts',
 'SciELO title_is_multidisciplinary',
 #[Sistema de Submissão 1 ou 0]
 'ScholarOne',
 'OJS',
 'Outros sistemas',
# [Dados de Google]
 'SciELO google_scholar_h5_2016',
 'SciELO google_scholar_m5_2016',
 #[Dados de Scopus]
 'Scopus title',
 'Scopus Publisher Main',
 'Scopus all_science_classification_codes_asjc',
 'Scopus coverage',
 'Scopus top_level_life_sciences',
 'Scopus top_level_social_sciences',
 'Scopus top_level_physical_sciences',
 'Scopus top_level_health_sciences',
 'Scopus 1000_general',
 'Scopus 1100_agricultural_and_biological_sciences',
 'Scopus 1200_arts_and_humanities',
 'Scopus 1300_biochemistry_genetics_and_molecular_biology',
 'Scopus 1400_business_management_and_accounting',
 'Scopus 1500_chemical_engineering',
 'Scopus 1600_chemistry',
 'Scopus 1700_computer_science',
 'Scopus 1800_decision_sciences',
 'Scopus 1900_earth_and_planetary_sciences',
 'Scopus 2000_economics_econometrics_and_finance',
 'Scopus 2100_energy',
 'Scopus 2200_engineering',
 'Scopus 2300_environmental_science',
 'Scopus 2400_immunology_and_microbiology',
 'Scopus 2500_materials_science',
 'Scopus 2600_mathematics',
 'Scopus 2700_medicine',
 'Scopus 2800_neuroscience',
 'Scopus 2900_nursing',
 'Scopus 3000_pharmacology_toxicology_and_pharmaceutics',
 'Scopus 3100_physics_and_astronomy',
 'Scopus 3200_psychology',
 'Scopus 3300_social_sciences',
 'Scopus 3400_veterinary',
 'Scopus 3500_dentistry',
 'Scopus 3600_health_professions',
 'Scopus 2013_citescore',
 'Scopus 2013_sjr',
 'Scopus 2013_snip',
 'Scopus 2014_citescore',
 'Scopus 2014_sjr',
 'Scopus 2014_snip',
 'Scopus 2015_citescore',
 'Scopus 2015_sjr',
 'Scopus 2015_snip',
#[Dados de Scimago]
 'Scimago title',
 'Scimago2013_active',
 'Scimago 2013_sjr',
 'Scimago 2013_sjr_best_quartile',
 'Scimago 2013_h_index',
 'Scimago 2013_total_docs_2015',
 'Scimago 2013_total_docs_3years',
 'Scimago 2013_total_refs',
 'Scimago 2013_total_cites_3years',
 'Scimago 2013_citable_docs_3years',
 'Scimago 2013_cites_doc_2years',
 'Scimago 2013_ref_doc',
 'Scimago 2014_active',
 'Scimago 2014_sjr',
 'Scimago 2014_sjr_best_quartile',
 'Scimago 2014_h_index',
 'Scimago 2014_total_docs_2015',
 'Scimago 2014_total_docs_3years',
 'Scimago 2014_total_refs',
 'Scimago 2014_total_cites_3years',
 'Scimago 2014_citable_docs_3years',
 'Scimago 2014_cites_doc_2years',
 'Scimago 2014_ref_doc',
 'Scimago 2015_active',
 'Scimago 2015_sjr',
 'Scimago 2015_sjr_best_quartile',
 'Scimago 2015_h_index',
 'Scimago 2015_total_docs_2015',
 'Scimago 2015_total_docs_3years',
 'Scimago 2015_total_refs',
 'Scimago 2015_total_cites_3years',
 'Scimago 2015_citable_docs_3years',
 'Scimago 2015_cites_doc_2years',
 'Scimago 2015_ref_doc',
 #[Dados de WoS]
 'WoS total_cites',
 'WoS journal_impact_factor',
 'WoS impact_factor_without_journal_self_cites',
 'WoS five_years_impact_factor',
 'WoS immediacy_index',
 'WoS citable_items',
 'WoS cited_half-life',
 'WoS citing_half-life',
 'WoS eigenfactor_score',
 'WoS article_influence_score',
 'WoS percentage_articles_in_citable_items',
 'WoS average_journal_impact_factor_percentile',
 'WoS normalized_eigenfactor']
