# coding: utf-8

scielo_headers = ['extraction date',
 'SciELO ou Scopus ou WoS',
 'SciELO',
 'Scopus',
 'WoS',
 'SciELO, Scopus e WoS',
 'SciELO e Scopus',
 'SciELO e WoS',
 'Scopus e WoS',
 'SciELO ou Scopus',
 'Scopus ou WoS',
 'SciELO ou WoS',
 'SciELO e (Scopus ou WoS)',
 'SciELO e não (Scopus)',
 '(Scopus ou WoS) e não SciELO',
 'Título (SciELO-Scopus-Wos)',
 # [Dados de SciELO]
 'ISSNs',
 'SciELO ISSN',
 'SciELO Status (corrente = 1; não corrente = 0)',
 'SciELO title thematic areas',
 'SciELO title is agricultural sciences',
 'SciELO title is applied social sciences',
 'SciELO title is biological sciences',
 'SciELO title is engineering',
 'SciELO title is exact and earth sciences',
 'SciELO title is health sciences',
 'SciELO title is human sciences',
 'SciELO title is linguistics, letters and arts',
 'SciELO title is multidisciplinary',
 'SciELO inclusion year',
 'SciELO stopping year',
 #[Sistema de Submissão 1 ou 0]
 'ScholarOne',
 'OJS',
 'Outros sistemas',
# [Dados de Google]
 'SciELO google scholar h5 2016',
 'SciELO google scholar m5 2016',
 #[Dados de Scopus]
 'Scopus title',
 'Scopus Publisher Main',
 'Scopus all science classification codes asjc',
 'Scopus coverage',
 'Scopus top level life sciences',
 'Scopus top level social sciences',
 'Scopus top level physical sciences',
 'Scopus top level health sciences',
 'Scopus 1000 general',
 'Scopus 1100 agricultural and biological sciences',
 'Scopus 1200 arts and humanities',
 'Scopus 1300 biochemistry genetics and molecular biology',
 'Scopus 1400 business management and accounting',
 'Scopus 1500 chemical engineering',
 'Scopus 1600 chemistry',
 'Scopus 1700 computer science',
 'Scopus 1800 decision sciences',
 'Scopus 1900 earth and planetary sciences',
 'Scopus 2000 economics econometrics and finance',
 'Scopus 2100 energy',
 'Scopus 2200 engineering',
 'Scopus 2300 environmental science',
 'Scopus 2400 immunology and microbiology',
 'Scopus 2500 materials science',
 'Scopus 2600 mathematics',
 'Scopus 2700 medicine',
 'Scopus 2800 neuroscience',
 'Scopus 2900 nursing',
 'Scopus 3000 pharmacology toxicology and pharmaceutics',
 'Scopus 3100 physics and astronomy',
 'Scopus 3200 psychology',
 'Scopus 3300 social sciences',
 'Scopus 3400 veterinary',
 'Scopus 3500 dentistry',
 'Scopus 3600 health professions',
 'Scopus 2013 citescore',
 'Scopus 2013 sjr',
 'Scopus 2013 snip',
 'Scopus 2014 citescore',
 'Scopus 2014 sjr',
 'Scopus 2014 snip',
 'Scopus 2015 citescore',
 'Scopus 2015 sjr',
 'Scopus 2015 snip',
#[Dados de Scimago]
 'Scimago title',
 'Scimago2013 active',
 'Scimago 2013 sjr',
 'Scimago 2013 sjr best quartile',
 'Scimago 2013 h index',
 'Scimago 2013 total docs 2015',
 'Scimago 2013 total docs 3years',
 'Scimago 2013 total refs',
 'Scimago 2013 total cites 3years',
 'Scimago 2013 citable docs 3years',
 'Scimago 2013 cites doc 2years',
 'Scimago 2013 ref doc',
 'Scimago 2014 active',
 'Scimago 2014 sjr',
 'Scimago 2014 sjr best quartile',
 'Scimago 2014 h index',
 'Scimago 2014 total docs 2015',
 'Scimago 2014 total docs 3years',
 'Scimago 2014 total refs',
 'Scimago 2014 total cites 3years',
 'Scimago 2014 citable docs 3years',
 'Scimago 2014 cites doc 2years',
 'Scimago 2014 ref doc',
 'Scimago 2015 active',
 'Scimago 2015 sjr',
 'Scimago 2015 sjr best quartile',
 'Scimago 2015 h index',
 'Scimago 2015 total docs 2015',
 'Scimago 2015 total docs 3years',
 'Scimago 2015 total refs',
 'Scimago 2015 total cites 3years',
 'Scimago 2015 citable docs 3years',
 'Scimago 2015 cites doc 2years',
 'Scimago 2015 ref doc',
 #[Dados de WoS]
 'WoS total cites',
 'WoS journal impact factor',
 'WoS impact factor without journal self cites',
 'WoS five years impact factor',
 'WoS immediacy index',
 'WoS citable items',
 'WoS cited half-life',
 'WoS citing half-life',
 'WoS eigenfactor score',
 'WoS article influence score',
 'WoS percentage articles in citable items',
 'WoS average journal impact factor percentile',
 'WoS normalized eigenfactor']
